version: "3"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: "Test123"
      MYSQL_DATABASE: "testdb"
    volumes: 
      - ./testdb:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"

  grpc: 
    build: .
    environment:
      DB_DRIVER: "mysql"
      DS_NAME: "root:Test123@tcp(db:3306)/testdb"
      MYSQL_HOST: "db"
      MYSQL_PASSWORD: "Test123"
      MYSQL_DB: "testdb"
      MYSQL_USER: "root"
      MYSQL_PORT: "3306"
    depends_on:
      - db
    command: ["go", "test", "-v", "./..."]
